### ISSUE TITLE
ModuleNotFoundError: No module named 'dataclasses' on Python 3.6

### ISSUE THREAD

**Issue by danieljfarrell** [FreeOpcUa/opcua-asyncio#295]
Hi folks,

Dataclasses were introduced in Python 3.7 but asyncua states that it supports Python 3.6. It is currently not usable on Python < 3.7.

Workaround is to install the backport,

    > pip search dataclasses
    dataclasses (0.7)                           - A backport of the dataclasses module for Python 3.6

A fix would be to include conditional in install requires,

```python
setup(
    # ...
    install_requires=[
        # ...
        "dataclasses; python_version<'3.7'",
    ]
)
```

**Comment by swamper123** [comment]
Since @oroulet once mentioned to drop support for 3.6 in #272, I would pick that up to affirm such a step as well.
The workaround may work, but I would prefere to be on a stable supported >=3.7 side, instead of using a workaround. Especially since users.py is using it and not another "minor feature".

**Comment by oroulet** [comment]
OK just pushed a commit to "fix" that. Especially the missing asyncio.run and create_tasks is always giving (small) issues

**Comment by danieljfarrell** [comment]
That's great! Thanks.
