### ISSUE TITLE
UASocketProtocol._process_received_data check _open_secure_channel_exchange

### ISSUE THREAD

**Issue by vruge** [FreeOpcUa/opcua-asyncio#914]
type `OpenSecureChannelResponse` has no member `RequestType`
```python
self._open_secure_channel_exchange = struct_from_binary(ua.OpenSecureChannelResponse, msg.body())
self._open_secure_channel_exchange.ResponseHeader.ServiceResult.check()
self._connection.set_channel(self._open_secure_channel_exchange.Parameters, params.RequestType, params.ClientNonce)
```
maybe `OpenSecureChannelParameters` is correct
```python
self._open_secure_channel_exchange = struct_from_binary(ua.OpenSecureChannelParameters, msg.body())
```

**Comment by schroeder-** [comment]
the code is correct but rly confusing
First self._open_secure_channel_exchange  is of type OpenSecureChannelParameters and then moved to variable params and then self._open_secure_channel_exchange  used as OpenSecureChannelResponse.

Because i don't want to break anything I annotated so that mypy is happy and it gives a little glue what is going on.
